services:

  backend:
    container_name: backend
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    env_file:
      - .env
    restart: always
    ports:
      - 5000:5000
    networks:
      - default

  frontend:
    container_name: frontend
    build: 
      context: ./frontend
    ports:
      - 3000:3000
    networks:
      - default
    volumes:
      - ./frontend:/app
    env_file:
      - .env
    restart: always

  bot:
    container_name: bot
    build: 
      context: ./bot
    networks:
      - default
    volumes:
      - ./bot:/app
    env_file:
      - .env
    restart: always

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - default
    volumes:
      - ./data:/data              
      - ./redis.conf:/usr/local/etc/redis/redis.conf 
    ports:
      - 6379:6379
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"] 
    restart: always


networks:
  default:
    driver: bridge
    name: cloude_voyage
